version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the Prometheus configuration file
    network_mode: host  # Connect to host network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set a default password for Grafana
      - GF_SECURITY_ADMIN_USER=admin
    network_mode: host  # Connect to host network
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana  # Persist Grafana data

volumes:
  grafana-storage:  # Volume for persisting Grafana data
