# prometheus.yml

global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scrapes itself (Prometheus)

  - job_name: 'simulator'
    static_configs:
      - targets: ['localhost:8000']  # Replace with your application's scrape target
