penalties:
  move_pod: 100
  unconnected_pod: 1000
  label: 1000
  latency: 100
  throughput: 10
  stability: 10
  spread: 10
  cpu: 10000000
  memory: 10000000

stability:
  floating_average_window: 30 # in minutes
  link_timeout: 90 # in seconds

scheduler:
  evolutionary:
    generations: 20
    children_per_parent: 10
    survivors_per_generation: 10
