penalties:
  move_pod: 100
  unconnected_pod: 1000
  label: 1000
  latency: 100
  throughput: 10
  stability: 10
  spread: 10

stability:
  floating_average_window: 30 # in minutes
  link_timeout: 30 # in seconds
