- name: Install Docker
  hosts: manager_group
  tasks:
    - name: Uninstall conflicting packages
      become: true
      shell: for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do apt-get remove $pkg; done
      ignore_errors: true
    - name: Add dockers official GPG key
      become: true
      shell: apt-get update && apt-get install ca-certificates curl && install -m 0755 -d /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && chmod a+r /etc/apt/keyrings/docker.asc
    - name: Add the repository to Apt sources
      become: true
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && apt-get update
    - name: Install Docker
      become: true
      shell: apt-get -yq install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - name: Add user to docker group
      become: true
      shell: usermod -aG docker {{ ansible_user }}
    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -